language: scala

scala:
  - 2.13.1

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

jobs:
  include:
    - env:
        - NAME="COMPILE"
        - SCALAC_FATAL_WARNINGS=true
      script:
        - sbt +compile

    - env:
        - NAME="TESTS"
        - SCALAC_FATAL_WARNINGS=true
      script:
        - sbt +test
